port: 8080
max_connections: 100
log_format: "[%s] [%s] [Client-%s] %s" # timestamp, level, client_id, message
udp_port: 8081
rate_limit: 5
rate_limited_log_interval: 10
log_path: "./logs/app.log"
log_max_size: 1048576 # 1MB
client_timeout: 30
allowed_levels:
  - "INFO"
  - "WARN"
  - "ERROR"
  - "DEBUG"
  - "AUDIT"